bagFolders = { ...
    'new_sharedcontrol.bag', ...
    'old_pot.bag', ...
    'no_support.bag'  ...
};

labels = {'Our Haptic Approach','Classical Potential Field','No Support'};

% Compare force feedback (Vector3) ...
compareVector3Cases( ...
    bagFolders, ...
    '/force_feedback/virtFix', ...
    'vector', ...
    labels, ...
    'Force Feedback Comparison' );


%% 3D trajectory for Case 1:
close
plotPose3DCase( ...
    bagFolders{1}, ...
    '/slave/state', ...
    labels{1} );
% 3D trajectory for Case 2:
close
plotPose3DCase( ...
    bagFolders{2}, ...
    '/slave/state', ...
    labels{2} );
% 3D trajectory for Case 2:
close
plotPose3DCase( ...
    bagFolders{3}, ...
    '/slave/state', ...
    labels{3} );

